[project]
name = "openai-agent-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "langsmith[openai-agents]>=0.3.14",
    "openai-agents>=0.1.0",
    "pytest>=8.4.1",
    "rich>=14.0.0",
]
